name: daily-job

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run job
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOP_JOBS_WEBHOOK_URL: ${{ secrets.TOP_JOBS_WEBHOOK_URL }}
          JOBS_WEBHOOK_URL: ${{ secrets.JOBS_WEBHOOK_URL }}
          LOW_SCORE_JOBS_WEBHOOK_URL: ${{ secrets.LOW_SCORE_JOBS_WEBHOOK_URL }}
          PERSON_INFO: ${{ secrets.PERSON_INFO }}
          PERSON_EXPERIENCE: ${{ secrets.PERSON_EXPERIENCE }}
          PERSON_SKILLS: ${{ secrets.PERSON_SKILLS }}
          LOCATION: ${{ secrets.LOCATION }}
          LINKEDIN_GEOID: ${{ secrets.LINKEDIN_GEOID }}
          TOP_JOB_ROLE_ID: ${{ secrets.TOP_JOB_ROLE_ID }}
          GOOD_JOB_ROLE_ID: ${{ secrets.GOOD_JOB_ROLE_ID }}
          EASY_APPLY_ROLE_ID: ${{ secrets.EASY_APPLY_ROLE_ID }}
          IGNORE_COMPANIES: ${{ secrets.IGNORE_COMPANIES }}
          RADIUS: ${{ secrets.RADIUS }}
        run: python main.py
