name: daily-job

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run job
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOP_JOBS_WEBHOOK_URL_1: ${{ secrets.TOP_JOBS_WEBHOOK_URL }}
          JOBS_WEBHOOK_URL_1: ${{ secrets.JOBS_WEBHOOK_URL }}
          LOW_SCORE_JOBS_WEBHOOK_URL_1: ${{ secrets.LOW_SCORE_JOBS_WEBHOOK_URL }}
          PERSON_INFO_1: ${{ secrets.PERSON_INFO_1 }}
          PERSON_EXPERIENCE_1: ${{ secrets.PERSON_EXPERIENCE_1 }}
          PERSON_SKILLS_1: ${{ secrets.PERSON_SKILLS_1 }}
          LOCATION: ${{ secrets.LOCATION }}
          LINKEDIN_GEOID: ${{ secrets.LINKEDIN_GEOID }}
          RADIUS_1: ${{ secrets.RADIUS_1 }}
          TOP_JOBS_WEBHOOK_URL_2: ${{ secrets.TOP_JOBS_WEBHOOK_URL_2 }}
          JOBS_WEBHOOK_URL_2: ${{ secrets.JOBS_WEBHOOK_URL_2 }}
          LOW_SCORE_JOBS_WEBHOOK_URL_2: ${{ secrets.LOW_SCORE_JOBS_WEBHOOK_URL_2 }}
          PERSON_INFO_2: ${{ secrets.PERSON_INFO_2 }}
          PERSON_EXPERIENCE_2: ${{ secrets.PERSON_EXPERIENCE_2 }}
          PERSON_SKILLS_2: ${{ secrets.PERSON_SKILLS_2 }}
          RADIUS_2: ${{ secrets.RADIUS_2 }}
        run: python main.py
